// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ContainerMounts extends pulumi.CustomResource {
    /**
     * Get an existing ContainerMounts resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContainerMountsState, opts?: pulumi.CustomResourceOptions): ContainerMounts {
        return new ContainerMounts(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'routeros:index/containerMounts:ContainerMounts';

    /**
     * Returns true if the given object is an instance of ContainerMounts.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContainerMounts {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContainerMounts.__pulumiType;
    }

    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___id_!: pulumi.Output<number | undefined>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___path_!: pulumi.Output<string | undefined>;
    public readonly containerMountsId!: pulumi.Output<string>;
    /**
     * Specifies destination path of the mount, which points to defined location in container
     */
    public readonly dst!: pulumi.Output<string>;
    /**
     * Name of the mount.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Specifies source path of the mount, which points to a RouterOS location
     */
    public readonly src!: pulumi.Output<string>;

    /**
     * Create a ContainerMounts resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContainerMountsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContainerMountsArgs | ContainerMountsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ContainerMountsState | undefined;
            resourceInputs["___id_"] = state ? state.___id_ : undefined;
            resourceInputs["___path_"] = state ? state.___path_ : undefined;
            resourceInputs["containerMountsId"] = state ? state.containerMountsId : undefined;
            resourceInputs["dst"] = state ? state.dst : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["src"] = state ? state.src : undefined;
        } else {
            const args = argsOrState as ContainerMountsArgs | undefined;
            if ((!args || args.dst === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dst'");
            }
            if ((!args || args.src === undefined) && !opts.urn) {
                throw new Error("Missing required property 'src'");
            }
            resourceInputs["___id_"] = args ? args.___id_ : undefined;
            resourceInputs["___path_"] = args ? args.___path_ : undefined;
            resourceInputs["containerMountsId"] = args ? args.containerMountsId : undefined;
            resourceInputs["dst"] = args ? args.dst : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["src"] = args ? args.src : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContainerMounts.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ContainerMounts resources.
 */
export interface ContainerMountsState {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    containerMountsId?: pulumi.Input<string>;
    /**
     * Specifies destination path of the mount, which points to defined location in container
     */
    dst?: pulumi.Input<string>;
    /**
     * Name of the mount.
     */
    name?: pulumi.Input<string>;
    /**
     * Specifies source path of the mount, which points to a RouterOS location
     */
    src?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ContainerMounts resource.
 */
export interface ContainerMountsArgs {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    containerMountsId?: pulumi.Input<string>;
    /**
     * Specifies destination path of the mount, which points to defined location in container
     */
    dst: pulumi.Input<string>;
    /**
     * Name of the mount.
     */
    name?: pulumi.Input<string>;
    /**
     * Specifies source path of the mount, which points to a RouterOS location
     */
    src: pulumi.Input<string>;
}
