// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIpv6Firewall(args?: GetIpv6FirewallArgs, opts?: pulumi.InvokeOptions): Promise<GetIpv6FirewallResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("routeros:index/getIpv6Firewall:getIpv6Firewall", {
        "___skip_": args.___skip_,
        "id": args.id,
        "rules": args.rules,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIpv6Firewall.
 */
export interface GetIpv6FirewallArgs {
    ___skip_?: string;
    id?: string;
    rules?: inputs.GetIpv6FirewallRule[];
}

/**
 * A collection of values returned by getIpv6Firewall.
 */
export interface GetIpv6FirewallResult {
    readonly ___skip_?: string;
    readonly id: string;
    readonly rules?: outputs.GetIpv6FirewallRule[];
}
export function getIpv6FirewallOutput(args?: GetIpv6FirewallOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIpv6FirewallResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("routeros:index/getIpv6Firewall:getIpv6Firewall", {
        "___skip_": args.___skip_,
        "id": args.id,
        "rules": args.rules,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIpv6Firewall.
 */
export interface GetIpv6FirewallOutputArgs {
    ___skip_?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    rules?: pulumi.Input<pulumi.Input<inputs.GetIpv6FirewallRuleArgs>[]>;
}
