// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSystemRouterboard(args?: GetSystemRouterboardArgs, opts?: pulumi.InvokeOptions): Promise<GetSystemRouterboardResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("routeros:index/getSystemRouterboard:getSystemRouterboard", {
        "___id_": args.___id_,
        "___path_": args.___path_,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSystemRouterboard.
 */
export interface GetSystemRouterboardArgs {
    ___id_?: number;
    ___path_?: string;
    id?: string;
}

/**
 * A collection of values returned by getSystemRouterboard.
 */
export interface GetSystemRouterboardResult {
    readonly ___id_?: number;
    readonly ___path_?: string;
    readonly currentFirmware: string;
    readonly factoryFirmware: string;
    readonly firmwareType: string;
    readonly id: string;
    readonly model: string;
    readonly revision: string;
    readonly routerboard: boolean;
    readonly serialNumber: string;
    readonly upgradeFirmware: string;
}
export function getSystemRouterboardOutput(args?: GetSystemRouterboardOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSystemRouterboardResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("routeros:index/getSystemRouterboard:getSystemRouterboard", {
        "___id_": args.___id_,
        "___path_": args.___path_,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSystemRouterboard.
 */
export interface GetSystemRouterboardOutputArgs {
    ___id_?: pulumi.Input<number>;
    ___path_?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
