// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class InterfaceOvpnServer extends pulumi.CustomResource {
    /**
     * Get an existing InterfaceOvpnServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InterfaceOvpnServerState, opts?: pulumi.CustomResourceOptions): InterfaceOvpnServer {
        return new InterfaceOvpnServer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'routeros:index/interfaceOvpnServer:InterfaceOvpnServer';

    /**
     * Returns true if the given object is an instance of InterfaceOvpnServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InterfaceOvpnServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InterfaceOvpnServer.__pulumiType;
    }

    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___id_!: pulumi.Output<number | undefined>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___path_!: pulumi.Output<string | undefined>;
    /**
     * The address of the remote side.
     */
    public /*out*/ readonly clientAddress!: pulumi.Output<string>;
    public readonly comment!: pulumi.Output<string | undefined>;
    public readonly disabled!: pulumi.Output<boolean | undefined>;
    /**
     * Encryption characteristics.
     */
    public /*out*/ readonly encoding!: pulumi.Output<string>;
    public readonly interfaceOvpnServerId!: pulumi.Output<string>;
    /**
     * Layer2 Maximum transmission unit. [See](https://wiki.mikrotik.com/wiki/Maximum_Transmission_Unit_on_RouterBoards).
     */
    public /*out*/ readonly mtu!: pulumi.Output<number>;
    /**
     * Interface name (Example: ovpn-in1).
     */
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly running!: pulumi.Output<boolean>;
    /**
     * Connection uptime.
     */
    public /*out*/ readonly uptime!: pulumi.Output<string>;
    /**
     * User name used for authentication.
     */
    public readonly user!: pulumi.Output<string | undefined>;

    /**
     * Create a InterfaceOvpnServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: InterfaceOvpnServerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InterfaceOvpnServerArgs | InterfaceOvpnServerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InterfaceOvpnServerState | undefined;
            resourceInputs["___id_"] = state ? state.___id_ : undefined;
            resourceInputs["___path_"] = state ? state.___path_ : undefined;
            resourceInputs["clientAddress"] = state ? state.clientAddress : undefined;
            resourceInputs["comment"] = state ? state.comment : undefined;
            resourceInputs["disabled"] = state ? state.disabled : undefined;
            resourceInputs["encoding"] = state ? state.encoding : undefined;
            resourceInputs["interfaceOvpnServerId"] = state ? state.interfaceOvpnServerId : undefined;
            resourceInputs["mtu"] = state ? state.mtu : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["running"] = state ? state.running : undefined;
            resourceInputs["uptime"] = state ? state.uptime : undefined;
            resourceInputs["user"] = state ? state.user : undefined;
        } else {
            const args = argsOrState as InterfaceOvpnServerArgs | undefined;
            resourceInputs["___id_"] = args ? args.___id_ : undefined;
            resourceInputs["___path_"] = args ? args.___path_ : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["disabled"] = args ? args.disabled : undefined;
            resourceInputs["interfaceOvpnServerId"] = args ? args.interfaceOvpnServerId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["user"] = args ? args.user : undefined;
            resourceInputs["clientAddress"] = undefined /*out*/;
            resourceInputs["encoding"] = undefined /*out*/;
            resourceInputs["mtu"] = undefined /*out*/;
            resourceInputs["running"] = undefined /*out*/;
            resourceInputs["uptime"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InterfaceOvpnServer.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering InterfaceOvpnServer resources.
 */
export interface InterfaceOvpnServerState {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    /**
     * The address of the remote side.
     */
    clientAddress?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    /**
     * Encryption characteristics.
     */
    encoding?: pulumi.Input<string>;
    interfaceOvpnServerId?: pulumi.Input<string>;
    /**
     * Layer2 Maximum transmission unit. [See](https://wiki.mikrotik.com/wiki/Maximum_Transmission_Unit_on_RouterBoards).
     */
    mtu?: pulumi.Input<number>;
    /**
     * Interface name (Example: ovpn-in1).
     */
    name?: pulumi.Input<string>;
    running?: pulumi.Input<boolean>;
    /**
     * Connection uptime.
     */
    uptime?: pulumi.Input<string>;
    /**
     * User name used for authentication.
     */
    user?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a InterfaceOvpnServer resource.
 */
export interface InterfaceOvpnServerArgs {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    interfaceOvpnServerId?: pulumi.Input<string>;
    /**
     * Interface name (Example: ovpn-in1).
     */
    name?: pulumi.Input<string>;
    /**
     * User name used for authentication.
     */
    user?: pulumi.Input<string>;
}
