// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpHotspotWalledGardenIp extends pulumi.CustomResource {
    /**
     * Get an existing IpHotspotWalledGardenIp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpHotspotWalledGardenIpState, opts?: pulumi.CustomResourceOptions): IpHotspotWalledGardenIp {
        return new IpHotspotWalledGardenIp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'routeros:index/ipHotspotWalledGardenIp:IpHotspotWalledGardenIp';

    /**
     * Returns true if the given object is an instance of IpHotspotWalledGardenIp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpHotspotWalledGardenIp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpHotspotWalledGardenIp.__pulumiType;
    }

    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___id_!: pulumi.Output<number | undefined>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___path_!: pulumi.Output<string | undefined>;
    /**
     * Action to perform, when packet matches the rule allow - allow access to the web-page without authorization deny - the
     * authorization is required to access the web-page reject - the authorization is required to access the resource, ICMP
     * reject message will be sent to client, when packet will match the rule.
     */
    public readonly action!: pulumi.Output<string | undefined>;
    public readonly comment!: pulumi.Output<string | undefined>;
    public readonly disabled!: pulumi.Output<boolean | undefined>;
    /**
     * Destination IP address, IP address of the WEB-server. Ignored if dst-host is already specified.
     */
    public readonly dstAddress!: pulumi.Output<string | undefined>;
    /**
     * Destination IP address list. Ignored if dst-host is already specified.
     */
    public readonly dstAddressList!: pulumi.Output<string | undefined>;
    /**
     * Domain name of the destination web-server. When this parameter is specified dynamic entry is added to Walled Garden.
     */
    public readonly dstHost!: pulumi.Output<string | undefined>;
    /**
     * TCP port number, client sends request to.
     */
    public readonly dstPort!: pulumi.Output<string | undefined>;
    public /*out*/ readonly invalid!: pulumi.Output<boolean>;
    public readonly ipHotspotWalledGardenIpId!: pulumi.Output<string>;
    /**
     * IP protocol.
     */
    public readonly protocol!: pulumi.Output<string | undefined>;
    /**
     * Name of the HotSpot server, rule is applied to.
     */
    public readonly server!: pulumi.Output<string | undefined>;
    /**
     * Source address of the user, usually IP address of the HotSpot client.
     */
    public readonly srcAddress!: pulumi.Output<string | undefined>;
    /**
     * Source IP address list.
     */
    public readonly srcAddressList!: pulumi.Output<string | undefined>;

    /**
     * Create a IpHotspotWalledGardenIp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IpHotspotWalledGardenIpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpHotspotWalledGardenIpArgs | IpHotspotWalledGardenIpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpHotspotWalledGardenIpState | undefined;
            resourceInputs["___id_"] = state ? state.___id_ : undefined;
            resourceInputs["___path_"] = state ? state.___path_ : undefined;
            resourceInputs["action"] = state ? state.action : undefined;
            resourceInputs["comment"] = state ? state.comment : undefined;
            resourceInputs["disabled"] = state ? state.disabled : undefined;
            resourceInputs["dstAddress"] = state ? state.dstAddress : undefined;
            resourceInputs["dstAddressList"] = state ? state.dstAddressList : undefined;
            resourceInputs["dstHost"] = state ? state.dstHost : undefined;
            resourceInputs["dstPort"] = state ? state.dstPort : undefined;
            resourceInputs["invalid"] = state ? state.invalid : undefined;
            resourceInputs["ipHotspotWalledGardenIpId"] = state ? state.ipHotspotWalledGardenIpId : undefined;
            resourceInputs["protocol"] = state ? state.protocol : undefined;
            resourceInputs["server"] = state ? state.server : undefined;
            resourceInputs["srcAddress"] = state ? state.srcAddress : undefined;
            resourceInputs["srcAddressList"] = state ? state.srcAddressList : undefined;
        } else {
            const args = argsOrState as IpHotspotWalledGardenIpArgs | undefined;
            resourceInputs["___id_"] = args ? args.___id_ : undefined;
            resourceInputs["___path_"] = args ? args.___path_ : undefined;
            resourceInputs["action"] = args ? args.action : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["disabled"] = args ? args.disabled : undefined;
            resourceInputs["dstAddress"] = args ? args.dstAddress : undefined;
            resourceInputs["dstAddressList"] = args ? args.dstAddressList : undefined;
            resourceInputs["dstHost"] = args ? args.dstHost : undefined;
            resourceInputs["dstPort"] = args ? args.dstPort : undefined;
            resourceInputs["ipHotspotWalledGardenIpId"] = args ? args.ipHotspotWalledGardenIpId : undefined;
            resourceInputs["protocol"] = args ? args.protocol : undefined;
            resourceInputs["server"] = args ? args.server : undefined;
            resourceInputs["srcAddress"] = args ? args.srcAddress : undefined;
            resourceInputs["srcAddressList"] = args ? args.srcAddressList : undefined;
            resourceInputs["invalid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpHotspotWalledGardenIp.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IpHotspotWalledGardenIp resources.
 */
export interface IpHotspotWalledGardenIpState {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    /**
     * Action to perform, when packet matches the rule allow - allow access to the web-page without authorization deny - the
     * authorization is required to access the web-page reject - the authorization is required to access the resource, ICMP
     * reject message will be sent to client, when packet will match the rule.
     */
    action?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    /**
     * Destination IP address, IP address of the WEB-server. Ignored if dst-host is already specified.
     */
    dstAddress?: pulumi.Input<string>;
    /**
     * Destination IP address list. Ignored if dst-host is already specified.
     */
    dstAddressList?: pulumi.Input<string>;
    /**
     * Domain name of the destination web-server. When this parameter is specified dynamic entry is added to Walled Garden.
     */
    dstHost?: pulumi.Input<string>;
    /**
     * TCP port number, client sends request to.
     */
    dstPort?: pulumi.Input<string>;
    invalid?: pulumi.Input<boolean>;
    ipHotspotWalledGardenIpId?: pulumi.Input<string>;
    /**
     * IP protocol.
     */
    protocol?: pulumi.Input<string>;
    /**
     * Name of the HotSpot server, rule is applied to.
     */
    server?: pulumi.Input<string>;
    /**
     * Source address of the user, usually IP address of the HotSpot client.
     */
    srcAddress?: pulumi.Input<string>;
    /**
     * Source IP address list.
     */
    srcAddressList?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IpHotspotWalledGardenIp resource.
 */
export interface IpHotspotWalledGardenIpArgs {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    /**
     * Action to perform, when packet matches the rule allow - allow access to the web-page without authorization deny - the
     * authorization is required to access the web-page reject - the authorization is required to access the resource, ICMP
     * reject message will be sent to client, when packet will match the rule.
     */
    action?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    /**
     * Destination IP address, IP address of the WEB-server. Ignored if dst-host is already specified.
     */
    dstAddress?: pulumi.Input<string>;
    /**
     * Destination IP address list. Ignored if dst-host is already specified.
     */
    dstAddressList?: pulumi.Input<string>;
    /**
     * Domain name of the destination web-server. When this parameter is specified dynamic entry is added to Walled Garden.
     */
    dstHost?: pulumi.Input<string>;
    /**
     * TCP port number, client sends request to.
     */
    dstPort?: pulumi.Input<string>;
    ipHotspotWalledGardenIpId?: pulumi.Input<string>;
    /**
     * IP protocol.
     */
    protocol?: pulumi.Input<string>;
    /**
     * Name of the HotSpot server, rule is applied to.
     */
    server?: pulumi.Input<string>;
    /**
     * Source address of the user, usually IP address of the HotSpot client.
     */
    srcAddress?: pulumi.Input<string>;
    /**
     * Source IP address list.
     */
    srcAddressList?: pulumi.Input<string>;
}
