// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Ipv6Settings extends pulumi.CustomResource {
    /**
     * Get an existing Ipv6Settings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ipv6SettingsState, opts?: pulumi.CustomResourceOptions): Ipv6Settings {
        return new Ipv6Settings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'routeros:index/ipv6Settings:Ipv6Settings';

    /**
     * Returns true if the given object is an instance of Ipv6Settings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ipv6Settings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ipv6Settings.__pulumiType;
    }

    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___id_!: pulumi.Output<number | undefined>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___path_!: pulumi.Output<string | undefined>;
    /**
     * Whether to accept ICMP redirect messages. Typically should be enabled on the host and disabled on routers.
     */
    public readonly acceptRedirects!: pulumi.Output<string | undefined>;
    /**
     * Accept router advertisement (RA) messages. If enabled, the router will be able to get the address using stateless
     * address configuration.
     */
    public readonly acceptRouterAdvertisements!: pulumi.Output<string | undefined>;
    /**
     * Enable/disable system wide IPv6 settings (prevents LL address generation).
     */
    public readonly disableIpv6!: pulumi.Output<boolean | undefined>;
    /**
     * Enable/disable packet forwarding between interfaces.
     */
    public readonly forward!: pulumi.Output<boolean | undefined>;
    public readonly ipv6SettingsId!: pulumi.Output<string>;
    /**
     * A maximum number or IPv6 neighbors. Since RouterOS version 7.1, the default value depends on the installed amount of
     * RAM. It is possible to set a higher value than the default, but it increases the risk of out-of-memory condition. The
     * default values for certain RAM sizes: * 1024 for 64 MB, * 2048 for 128 MB, * 4096 for 256 MB, * 8192 for 512 MB, * 16384
     * for 1024 MB or higher.
     */
    public readonly maxNeighborEntries!: pulumi.Output<number | undefined>;
    /**
     * IPv6 Hash policy used for ECMP routing in `/ipv6/settings` menu * l3 -- layer-3 hashing of src IP, dst IP, flow label,
     * IP protocol * l3-inner -- layer-3 hashing or inner layer-3 hashing if available * l4 -- layer-4 hashing of src IP, dst
     * IP, IP protocol, src port, dst port.
     */
    public readonly multipathHashPolicy!: pulumi.Output<string | undefined>;

    /**
     * Create a Ipv6Settings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: Ipv6SettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ipv6SettingsArgs | Ipv6SettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ipv6SettingsState | undefined;
            resourceInputs["___id_"] = state ? state.___id_ : undefined;
            resourceInputs["___path_"] = state ? state.___path_ : undefined;
            resourceInputs["acceptRedirects"] = state ? state.acceptRedirects : undefined;
            resourceInputs["acceptRouterAdvertisements"] = state ? state.acceptRouterAdvertisements : undefined;
            resourceInputs["disableIpv6"] = state ? state.disableIpv6 : undefined;
            resourceInputs["forward"] = state ? state.forward : undefined;
            resourceInputs["ipv6SettingsId"] = state ? state.ipv6SettingsId : undefined;
            resourceInputs["maxNeighborEntries"] = state ? state.maxNeighborEntries : undefined;
            resourceInputs["multipathHashPolicy"] = state ? state.multipathHashPolicy : undefined;
        } else {
            const args = argsOrState as Ipv6SettingsArgs | undefined;
            resourceInputs["___id_"] = args ? args.___id_ : undefined;
            resourceInputs["___path_"] = args ? args.___path_ : undefined;
            resourceInputs["acceptRedirects"] = args ? args.acceptRedirects : undefined;
            resourceInputs["acceptRouterAdvertisements"] = args ? args.acceptRouterAdvertisements : undefined;
            resourceInputs["disableIpv6"] = args ? args.disableIpv6 : undefined;
            resourceInputs["forward"] = args ? args.forward : undefined;
            resourceInputs["ipv6SettingsId"] = args ? args.ipv6SettingsId : undefined;
            resourceInputs["maxNeighborEntries"] = args ? args.maxNeighborEntries : undefined;
            resourceInputs["multipathHashPolicy"] = args ? args.multipathHashPolicy : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ipv6Settings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Ipv6Settings resources.
 */
export interface Ipv6SettingsState {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    /**
     * Whether to accept ICMP redirect messages. Typically should be enabled on the host and disabled on routers.
     */
    acceptRedirects?: pulumi.Input<string>;
    /**
     * Accept router advertisement (RA) messages. If enabled, the router will be able to get the address using stateless
     * address configuration.
     */
    acceptRouterAdvertisements?: pulumi.Input<string>;
    /**
     * Enable/disable system wide IPv6 settings (prevents LL address generation).
     */
    disableIpv6?: pulumi.Input<boolean>;
    /**
     * Enable/disable packet forwarding between interfaces.
     */
    forward?: pulumi.Input<boolean>;
    ipv6SettingsId?: pulumi.Input<string>;
    /**
     * A maximum number or IPv6 neighbors. Since RouterOS version 7.1, the default value depends on the installed amount of
     * RAM. It is possible to set a higher value than the default, but it increases the risk of out-of-memory condition. The
     * default values for certain RAM sizes: * 1024 for 64 MB, * 2048 for 128 MB, * 4096 for 256 MB, * 8192 for 512 MB, * 16384
     * for 1024 MB or higher.
     */
    maxNeighborEntries?: pulumi.Input<number>;
    /**
     * IPv6 Hash policy used for ECMP routing in `/ipv6/settings` menu * l3 -- layer-3 hashing of src IP, dst IP, flow label,
     * IP protocol * l3-inner -- layer-3 hashing or inner layer-3 hashing if available * l4 -- layer-4 hashing of src IP, dst
     * IP, IP protocol, src port, dst port.
     */
    multipathHashPolicy?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ipv6Settings resource.
 */
export interface Ipv6SettingsArgs {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    /**
     * Whether to accept ICMP redirect messages. Typically should be enabled on the host and disabled on routers.
     */
    acceptRedirects?: pulumi.Input<string>;
    /**
     * Accept router advertisement (RA) messages. If enabled, the router will be able to get the address using stateless
     * address configuration.
     */
    acceptRouterAdvertisements?: pulumi.Input<string>;
    /**
     * Enable/disable system wide IPv6 settings (prevents LL address generation).
     */
    disableIpv6?: pulumi.Input<boolean>;
    /**
     * Enable/disable packet forwarding between interfaces.
     */
    forward?: pulumi.Input<boolean>;
    ipv6SettingsId?: pulumi.Input<string>;
    /**
     * A maximum number or IPv6 neighbors. Since RouterOS version 7.1, the default value depends on the installed amount of
     * RAM. It is possible to set a higher value than the default, but it increases the risk of out-of-memory condition. The
     * default values for certain RAM sizes: * 1024 for 64 MB, * 2048 for 128 MB, * 4096 for 256 MB, * 8192 for 512 MB, * 16384
     * for 1024 MB or higher.
     */
    maxNeighborEntries?: pulumi.Input<number>;
    /**
     * IPv6 Hash policy used for ECMP routing in `/ipv6/settings` menu * l3 -- layer-3 hashing of src IP, dst IP, flow label,
     * IP protocol * l3-inner -- layer-3 hashing or inner layer-3 hashing if available * l4 -- layer-4 hashing of src IP, dst
     * IP, IP protocol, src port, dst port.
     */
    multipathHashPolicy?: pulumi.Input<string>;
}
