// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WifiSteering extends pulumi.CustomResource {
    /**
     * Get an existing WifiSteering resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WifiSteeringState, opts?: pulumi.CustomResourceOptions): WifiSteering {
        return new WifiSteering(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'routeros:index/wifiSteering:WifiSteering';

    /**
     * Returns true if the given object is an instance of WifiSteering.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WifiSteering {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WifiSteering.__pulumiType;
    }

    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___id_!: pulumi.Output<number | undefined>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    public readonly ___path_!: pulumi.Output<string | undefined>;
    public readonly comment!: pulumi.Output<string | undefined>;
    public readonly disabled!: pulumi.Output<boolean | undefined>;
    /**
     * Name of the steering profile.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Neighbor group of potential roaming candidates.
     */
    public readonly neighborGroups!: pulumi.Output<string[] | undefined>;
    /**
     * An option to enable sending 802.11k neighbor reports.
     */
    public readonly rrm!: pulumi.Output<boolean | undefined>;
    public readonly wifiSteeringId!: pulumi.Output<string>;
    /**
     * An option to enable sending 802.11v BSS transition management requests.
     */
    public readonly wnm!: pulumi.Output<boolean | undefined>;

    /**
     * Create a WifiSteering resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WifiSteeringArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WifiSteeringArgs | WifiSteeringState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WifiSteeringState | undefined;
            resourceInputs["___id_"] = state ? state.___id_ : undefined;
            resourceInputs["___path_"] = state ? state.___path_ : undefined;
            resourceInputs["comment"] = state ? state.comment : undefined;
            resourceInputs["disabled"] = state ? state.disabled : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["neighborGroups"] = state ? state.neighborGroups : undefined;
            resourceInputs["rrm"] = state ? state.rrm : undefined;
            resourceInputs["wifiSteeringId"] = state ? state.wifiSteeringId : undefined;
            resourceInputs["wnm"] = state ? state.wnm : undefined;
        } else {
            const args = argsOrState as WifiSteeringArgs | undefined;
            resourceInputs["___id_"] = args ? args.___id_ : undefined;
            resourceInputs["___path_"] = args ? args.___path_ : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["disabled"] = args ? args.disabled : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["neighborGroups"] = args ? args.neighborGroups : undefined;
            resourceInputs["rrm"] = args ? args.rrm : undefined;
            resourceInputs["wifiSteeringId"] = args ? args.wifiSteeringId : undefined;
            resourceInputs["wnm"] = args ? args.wnm : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WifiSteering.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering WifiSteering resources.
 */
export interface WifiSteeringState {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    /**
     * Name of the steering profile.
     */
    name?: pulumi.Input<string>;
    /**
     * Neighbor group of potential roaming candidates.
     */
    neighborGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * An option to enable sending 802.11k neighbor reports.
     */
    rrm?: pulumi.Input<boolean>;
    wifiSteeringId?: pulumi.Input<string>;
    /**
     * An option to enable sending 802.11v BSS transition management requests.
     */
    wnm?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a WifiSteering resource.
 */
export interface WifiSteeringArgs {
    /**
     * <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
     */
    ___id_?: pulumi.Input<number>;
    /**
     * <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
     */
    ___path_?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    disabled?: pulumi.Input<boolean>;
    /**
     * Name of the steering profile.
     */
    name?: pulumi.Input<string>;
    /**
     * Neighbor group of potential roaming candidates.
     */
    neighborGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * An option to enable sending 802.11k neighbor reports.
     */
    rrm?: pulumi.Input<boolean>;
    wifiSteeringId?: pulumi.Input<string>;
    /**
     * An option to enable sending 802.11v BSS transition management requests.
     */
    wnm?: pulumi.Input<boolean>;
}
